name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
    paths:
      - '**.md'  # Only trigger if .md files are changed

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex

    - name: Convert Markdown to PDF
      run: |
        mkdir -p pdfs
        for file in $(find . -name "*.md"); do
          pdf_name="pdfs/$(basename "$file" .md).pdf"
          pandoc "$file" -o "$pdf_name" --pdf-engine=xelatex
        done

    - name: Upload PDFs as artifact
      uses: actions/upload-artifact
      with:
        name: pdf-files
        path: output/
