name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex

    - name: Convert Markdown to PDF
      run: |
        mkdir -p pdfs
        find . -name "*.md" -print0 | while IFS= read -r -d '' file; do
          echo "Processing file: $file"
          pdf_name="pdfs/$(basename "$file" .md).pdf"
          pandoc "$file" -o "$pdf_name" --pdf-engine=xelatex || echo "Error processing $file"
        done

    - name: Upload PDFs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-files
        path: pdfs/
